version: "3.7"

services:
  app-efishery:
    container_name: eifhsery
    build:
      context: .
      dockerfile: Dockerfile
    image: efishery-go:1.0
    env_file:
      - .env
    ports:
    - 8080:8080
    networks:
      - go_network


networks:
    go_network:
      name: go_network

